# Copyright Kani Contributors
# SPDX-License-Identifier: Apache-2.0 OR MIT

[package]
name = "kani_macros"
version = "0.28.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
proc-macro-error = "1.0.4"
quote = "1.0.20"
syn = { version = "1.0", features = ["full", "parsing", "printing", "visit-mut", "visit", "extra-traits", "clone-impls"]}
uuid = { version = "1.0", features = ["v4"] }
>>>>>>> Add procedural macros for function contracts. (#1552)
